packages/app/src/App.tsx
packages/app/src/views/Home.tsx
packages/app/src/views/MobileHome.tsx

Ne pas valider tout de suite : à synchroniser avec les ops et les maj des autres applis (notamment cdtn et le site de l'incubateur)

maj matomo + wording

---

packages/app/src/AppReducer.tsx

feat(informations): invalider les effectifs lors d'un changement d'informations

---

packages/app/src/views/Indicateur1/IndicateurUn.tsx
packages/app/src/views/Indicateur1/IndicateurUnCoef/IndicateurUnCoefRemuForm.tsx
packages/app/src/views/Indicateur1/IndicateurUnCsp/IndicateurUnCsp.tsx
packages/app/src/views/Indicateur1/IndicateurUnCsp/IndicateurUnCspForm.tsx

fix(50 à 250): le bouton 'suivant' de l'indicateur 1 dépend de la tranche d'effectifs

---

packages/app/src/views/Informations/Informations.tsx

fix(informations): supprimer les liens vers les indicateurs invalidés lors d'une modification des informations

---

packages/app/src/AppReducer.tsx

feat(informations): invalider toutes les données lors d'une modification des informations

---

packages/app/package.json
packages/app/src/utils/formHelpers.tsx
packages/app/src/utils/helpers.test.tsx
packages/app/src/utils/helpers.tsx
packages/app/src/views/Indicateur2et3/IndicateurDeuxTroisForm.tsx
packages/app/src/views/Informations/InformationsForm.tsx
yarn.lock

Fixes #240, #233
Cette PR rajoute un datepicker compatible IE11, et réactive la saisie des deux dates (début et fin), avec auto-calcul de l'autre date.

feat(informations): utilisation d'un datepicker compatible IE11

---

packages/app/src/components/Button.tsx
packages/app/src/views/Informations/InformationsForm.tsx

Fixes #269
Aperçu du résultat sur Firefox:

fix(css): suppression des z-index, whitespace sur les datepicker

---

packages/app/src/components/CellInput.tsx
packages/app/src/views/FAQ/FAQ.tsx
packages/app/src/views/FAQ/FAQSection.tsx
packages/app/src/views/FAQ/FAQSectionDetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQIndicateur1DetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQIndicateur2DetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQIndicateur2et3DetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQIndicateur3DetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQIndicateur4DetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQIndicateur5DetailCalcul.tsx
packages/app/src/views/FAQ/components-detail-calcul/FAQResultatDetailCalcul.tsx
packages/app/src/views/FAQ/components/FAQCalculScale.tsx
packages/app/src/views/FAQ/components/FAQHeader.tsx
packages/app/src/views/FAQ/components/FAQStep.tsx
packages/app/src/views/FAQ/components/FAQTitle3.tsx

Faq enhancement

---

.env.sample
.gitlab-ci.yml
.travis.yml
package.json
packages/app/cypress.json
packages/app/cypress/fixtures/example.json
packages/app/cypress/integration/desktop_full_simulation_spec.js
packages/app/cypress/plugins/index.js
packages/app/cypress/support/commands.js
packages/app/cypress/support/index.js
packages/app/package.json
packages/app/src/views/Informations/InformationsForm.tsx
yarn.lock

feat(integration tests): ajout de tests end to end via cypress

---

packages/app/src/components/Footer.tsx

feat(version): ajout du numéro de version déployé dans le footer

---

docker-compose.yml
packages/kinto/Pipfile
packages/kinto/Pipfile.lock
packages/kinto/README.md
packages/kinto/import-solen.py

Importation des données Solen dans Kinto.

---

packages/kinto/import-solen.py

Je viens de tester l'import sur la collection `indicators_data`, et ils 'avère qu'il faut utiliser un objet particulier pour patcher la collection avec le schéma quand il est manquant. Ce patch corrige le souci.

Correction de l'ajout du schéma sur la collection si absent.

---

packages/kinto/.gitignore
packages/kinto/Pipfile
packages/kinto/Pipfile.lock
packages/kinto/README.md
packages/kinto/import-solen.py
packages/kinto/json-schema.json

Passage a Excel (.xlsx) comme source de données.

---

packages/app/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx

fix(declaration): ne pas demander le nom de l'UES si la structure est Entreprise

---

packages/app/src/AppReducer.test.tsx
packages/app/src/AppReducer.tsx
packages/app/src/__fixtures__/stateComplete.tsx
packages/app/src/__snapshots__/AppReducer.test.tsx.snap
packages/app/src/globals.d.ts
packages/app/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx

fix(declaration): suppression des champs des effectifs globaux

---

packages/app/src/views/InformationsComplementaires/InformationsComplementaires.tsx
packages/app/src/views/InformationsComplementaires/InformationsComplementairesForm.tsx
packages/kinto/json-schema.json

feat(declaration): ne demande la date de consultation du CSE que si indicateur 1 pas par CSP

---

packages/app/src/views/Indicateur5/IndicateurCinqForm.tsx
packages/kinto/json-schema.json

fix(indicateur5): ne demander qu'une seule donnée et calculer l'autre automatiquement

---

packages/app/src/views/Declaration/Declaration.tsx
packages/kinto/json-schema.json

feat(declaration): affichage de l'index global sur la page de déclaration

---

packages/app/src/AppReducer.tsx
packages/app/src/views/InformationsComplementaires/InformationsComplementairesForm.tsx

fix(declaration): permettre la validation de "informations complémentaires" si la date de consultation du CSE n'est pas demandée

---

packages/app/src/views/InformationsDeclarant/InformationsDeclarantForm.tsx

feat(declaration): validation du format de l'adresse email

---

packages/app/src/views/InformationsDeclarant/InformationsDeclarantForm.tsx

feat(declaration): validation du format du numéro de téléphone

---

packages/app/src/views/FAQ/components/FAQFooter.tsx

feat(declaration): ajout du numéro "Allô Index Egapro"

---

packages/app/src/containers/MainScrollView.tsx
packages/app/src/views/Recapitulatif/Recapitulatif.tsx

fix(declaration): impression de la totalité du récapitulatif

---

packages/app/src/components/AnneeDeclaration.tsx
packages/app/src/views/InformationsComplementaires/InformationsComplementairesForm.tsx

feat(declaration): l'année de déclaration se choisit dans une liste déroulante

---

packages/app/src/components/Footer.tsx
packages/app/src/containers/AppLayout.tsx
packages/app/src/views/FAQ/FAQ.tsx
packages/app/src/views/MentionsLegales.tsx

feat(RGPD): ajout d'une page 'mentions légales'

---

packages/app/src/AppReducer.tsx
packages/app/src/__fixtures__/stateComplete.tsx
packages/app/src/__snapshots__/AppReducer.test.tsx.snap
packages/app/src/globals.d.ts
packages/app/src/views/InformationsComplementaires/InformationsComplementairesForm.tsx
packages/app/src/views/InformationsSimulation/InformationsSimulationForm.tsx
packages/kinto/solen.py

Fix(declaration): le champ "année de déclaration" est demandé en tout début de simulation

---

packages/kinto/json-schema.json
packages/kinto/solen.py

fix(import solen): import des données de l'indicateur1 même dans le cas d'une modalité AMC (autre)

---

packages/app/public/index.html
packages/app/src/AppReducer.test.tsx
packages/app/src/AppReducer.tsx
packages/app/src/__fixtures__/stateComplete.tsx
packages/app/src/__snapshots__/AppReducer.test.tsx.snap
packages/app/src/components/Footer.tsx
packages/app/src/containers/AppLayout.tsx
packages/app/src/globals.d.ts
packages/app/src/views/CGU.tsx
packages/app/src/views/FAQ/FAQ.tsx
packages/app/src/views/InformationsDeclarant/InformationsDeclarantForm.tsx
packages/kinto/json-schema.json

Feat(CGU): ajout d'une page de CGU

---

packages/app/src/AppReducer.test.tsx
packages/app/src/AppReducer.tsx
packages/app/src/__snapshots__/AppReducer.test.tsx.snap
packages/app/src/globals.d.ts
packages/app/src/views/Indicateur1/IndicateurUn.tsx
packages/app/src/views/Indicateur1/IndicateurUnTypeForm.tsx
packages/kinto/solen.py

feat(declaration): rajout d'une modalité "autre" à la déclaration de l'indicateur 1

---

packages/app/src/components/Menu.tsx
packages/app/src/views/Declaration/Declaration.tsx
packages/app/src/views/Declaration/DeclarationForm.tsx
packages/app/src/views/Indicateur2/IndicateurDeux.tsx
packages/app/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx
packages/app/src/views/Indicateur3/IndicateurTrois.tsx
packages/app/src/views/Indicateur4/IndicateurQuatre.tsx
packages/app/src/views/Recapitulatif/RecapitulatifIndex.tsx
packages/app/src/views/Recapitulatif/RecapitulatifInformations.tsx

fix(declaration): prise en compte des retours de la DGT (ter)

---

packages/app/cypress/integration/desktop_full_simulation_spec.js
packages/app/src/components/AnneeDeclaration.tsx
packages/app/src/components/FieldDate.tsx
packages/app/src/views/InformationsSimulation/InformationsSimulationForm.tsx

Fix(declaration): l'année est au titre de laquelle les indicateurs sont calculés

---

packages/app/src/components/Header.tsx
packages/app/src/views/Home.tsx
packages/app/src/views/MobileHome.tsx

fix(declaration): changement de la home pour parler de la déclaration

---

packages/app/src/views/Declaration/Declaration.tsx
packages/app/src/views/Home.tsx
packages/app/src/views/Recapitulatif/Recapitulatif.tsx
packages/app/src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx

fix(declaration): forcer la déclaration de l'indicateur 1 par CSP si il n'est pas calculable par coefficient

---

packages/app/src/components/Menu.tsx
packages/app/src/containers/AppLayout.tsx
packages/app/src/index.css
packages/app/src/views/FAQ/FAQ.tsx

fix(layout): amélioration du layout tablet

---

packages/app/src/utils/helpers.tsx
packages/app/src/views/Indicateur2/IndicateurDeux.tsx
packages/app/src/views/Indicateur2/IndicateurDeuxResult.tsx
packages/app/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx
packages/app/src/views/Indicateur2et3/IndicateurDeuxTroisResult.tsx
packages/app/src/views/Indicateur3/IndicateurTrois.tsx
packages/app/src/views/Indicateur3/IndicateurTroisResult.tsx
packages/app/src/views/Recapitulatif/Recapitulatif.tsx
packages/app/src/views/Recapitulatif/RecapitulatifIndicateurDeux.tsx
packages/app/src/views/Recapitulatif/RecapitulatifIndicateurDeuxTrois.tsx
packages/app/src/views/Recapitulatif/RecapitulatifIndicateurQuatre.tsx
packages/app/src/views/Recapitulatif/RecapitulatifIndicateurTrois.tsx

Prise en compte des retours de la DGT (4)

---

packages/app/src/utils/helpers.tsx
packages/app/src/views/Indicateur2/IndicateurDeux.tsx
packages/app/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx
packages/app/src/views/Indicateur3/IndicateurTrois.tsx

Demande de Laurane :
> l y aurait un petit ajout à faire en termes de formulation : "L'écart de taux d'augmentations est en faveur des..." ... "donc l'écart de taux d'augmentations est considéré comme une mesure de correction".

Reformulation du message de mesure de corrections

---

packages/api/src/controller/index.ts
packages/api/src/controller/stats.controller.ts
packages/api/src/model/index.ts
packages/api/src/model/stats-data.model.ts
packages/api/src/repository/index.ts
packages/api/src/repository/kinto-api.ts
packages/api/src/repository/stats-data.repository.ts
packages/api/src/routes.ts
packages/api/src/service/index.ts
packages/api/src/service/stats/index.ts
packages/api/src/service/stats/stats.service.ts

feat(api): ajout d'un endpoint /stats

---

packages/app/src/App.tsx
packages/app/src/components/Header.tsx
packages/app/src/components/InfoBloc.tsx

feat(declaration): affichage d'un bandeau pour prévenir d'une interruption de service

---

packages/app/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx

Fixes #527
Proposition de présentation et d'explication :

fix(declaration): afficher une ligne de moins que le nombre d'entreprises composant l'UES dans le formulaire "informations entreprise/UES"

---

.github/renovate.json
renovate.json

chore(renovate): use our SocialGouv/renovate-config

---

.gitlab-ci/stages/05-deploy.yml

---
Explicit the docker image url to be renovate friendly

ci(gitlab): update socialgouv/docker/kubectl to 0.29.0

---

.gitlab-ci/stages/05-deploy.yml

build(k8s): disable hpa for app and api in dev

---

packages/app/server.js

Breaking change introduced in #535

fix(app): utilisation de createProxyMiddleware suite à maj de http-proxy-middleware

---

.gitlab-ci.yml
.gitlab-ci/stages/01-quality.yml

ci(gitlab): parallel lint build test jobs

---

.gitlab-ci/stages/01-quality.yml

ci(gitlab): remove actual node_modules from gitlab cache

---

.gitlab-ci/stages/01-quality.yml

ci(gitlab): separate app and api tests

---

.gitlab-ci.yml
.gitlab-ci/stages/07-notify.yml

ci(gitlab): send link with protocol to github

---

.k8s/import-export/import-export-job.yml
packages/import-export/import-export.sh

fix(import-export): use local and prod kinto admin passwords

---

.dockerignore
.gitlab-ci/stages/03-register.yml
.gitlab-ci/stages/06-release.yml
.k8s/migrate-data/migrate-data-job.yml
packages/app/Dockerfile.migrate-data
packages/app/src/migrations/533-initial-migrations.ts

feat(migration): Migration des données dans le pipeline gitlab

---

src/views/Declaration/Declaration.tsx

https://trello.com/c/BnN3cIDF/29-simulation-d%C3%A9claration-imposer-un-passage-sur-toutes-les-pages-pour-valider-la-d%C3%A9claration

fix: info & effectifs pages are mandatory now

---

src/components/ds/SelectGroup.tsx
src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx
src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx

- years readonly but could change value
- name ues was unfillable
- percentage for remuneration was missing

Fix: bugs 

---

src/components/Header.tsx

feat: add disconnected menu

---

.github/workflows/tests.yml
packages/app/__tests__/components/Span.test.tsx
packages/app/__tests__/components/__snapshots__/Span.test.tsx.snap
packages/app/__tests__/components/ds/ActivityIndicator.test.tsx
packages/app/__tests__/components/ds/AlertSpinner.test.tsx
packages/app/__tests__/components/ds/Banner.test.tsx
packages/app/__tests__/components/ds/ButtonAction.test.tsx
packages/app/__tests__/components/ds/Footer.test.tsx
packages/app/__tests__/components/ds/Header.test.tsx
packages/app/__tests__/components/ds/LinkButton.test.tsx
packages/app/__tests__/components/ds/Logo.test.tsx
packages/app/__tests__/components/ds/SinglePageLayout.test.tsx
packages/app/__tests__/components/ds/TextLink.test.tsx
packages/app/__tests__/components/ds/__snapshots__/ActivityIndicator.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/AlertSpinner.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/Banner.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/ButtonAction.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/Footer.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/Header.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/LinkButton.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/Logo.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/SinglePageLayout.test.tsx.snap
packages/app/__tests__/components/ds/__snapshots__/TextLink.test.tsx.snap
packages/app/jest.config.js
packages/app/package.json
sonar-project.properties

- Configured Sonar cloud
- Configured jest coverage report
- Init snapshot for simple components

test(app): setup test coverage and init snapshot

---

packages/api/egapro/pdf/declaration.py
packages/api/test/test_email.py

feat: repatriate missing commit

---

packages/app/src/pages/index.tsx
packages/simulateur/src/components/ErrorMessage.tsx
packages/simulateur/src/components/FieldSiren.tsx
packages/simulateur/src/components/MailtoLink.tsx
packages/simulateur/src/components/ds/NoSiren.tsx
packages/simulateur/src/containers/Simulateur.tsx
packages/simulateur/src/views/AskEmail.tsx
packages/simulateur/src/views/Declaration/DeclarationForm.tsx
packages/simulateur/src/views/Home.tsx

feat: wordings

---

packages/api/egapro/constants.py
packages/api/egapro/views.py
packages/api/test/api/test_declaration.py

Added get declaration endpoint for rep-eq
Added error handling decorator
Added/fixed tests

feat: added get declaration endpoint for rep-eq

---

packages/simulateur/src/components/FieldSiren.tsx

feat: add a br before email

---

packages/simulateur/src/hooks/useDeclaration.ts

feat: refactor with new endpoint /declarations

---

packages/declaration/src/commencer.html

feat: add a br in wording

---

packages/app/.env.production

fix(app): bad redirection for declaration

---

packages/app/src/design-system/base/ButtonAsLink.tsx

Co-authored-by: Laurent Sutterlity <laurent@sutterlity.studio>
Closes #1068

fix: wrap ButtonAsLink into forwardRef

---

packages/app/__stories__/Callout.stories.tsx
packages/app/__tests__/design-system/base/Callout.test.tsx
packages/app/__tests__/design-system/base/__snapshots__/Callout.test.tsx.snap
packages/app/src/design-system/base/Callout.module.css
packages/app/src/design-system/base/Callout.tsx
packages/app/src/design-system/index.ts
packages/app/src/design-system/utils/icon-styles.ts

feat(app): Add Callout component

---

packages/simulateur/src/hooks/useDeclaration.ts

fix: restore fetch all years functionality

---

packages/app/__stories__/FormRadio.stories.tsx
packages/app/__tests__/design-system/base/FormRadio.test.tsx
packages/app/__tests__/design-system/base/__snapshots__/FormRadio.test.tsx.snap
packages/app/src/design-system/base/FormRadio.tsx
packages/app/src/design-system/index.ts

feat(app): add radio button

---

packages/simulateur/src/views/Indicateur2/IndicateurDeuxForm.tsx
packages/simulateur/src/views/Indicateur3/IndicateurTroisForm.tsx

fix: typo sur Pourcentages

---

packages/simulateur/src/utils/declarationBuilder.ts
packages/simulateur/src/utils/helpers.ts
packages/simulateur/src/views/Declaration/DeclarationForm.tsx

fix: bug on mesures correction + CSE

---

packages/app/src/pages/ecart-rep/declarant.tsx

feat: add page infos déclarant

feat: add page informations declarant

---

packages/api/egapro/pdf/declaration.py

Fix none cell issue in PDF display

fix: None cell issue in objectives pdf

---

packages/simulateur/src/components/FieldPlanRelance.tsx
packages/simulateur/src/views/Declaration/DeclarationForm.tsx

fix: planRelance was required even for decla before 2021. Fixed

---

packages/app/src/pages/ecart-rep/periode-reference.tsx

chore: typo periode reference

---

packages/api/egapro/pdf/declaration.py

- Ref https://github.com/SocialGouv/egapro/pull/1139
- cherry-pick fix in prod

fix: None cell issue in objectives pdf (prod)

---

packages/app/src/pages/ecart-rep/assujetti.tsx

feat: next page after assujetti is commencer for authenticated user

---

packages/app/src/pages/ecart-rep/ecarts-membres.tsx
packages/app/src/services/apiClient/useFormManager.ts

feat: page ecarts membres validation

---

packages/app/src/pages/ecart-rep/validation.tsx

fix: validation page types

---

packages/app/src/pages/ecart-rep/commencer.tsx
packages/app/src/services/apiClient/repartition.ts
packages/app/src/services/apiClient/useUser.tsx

feat: stop on commencer if a repeq already exists

---

packages/declaration/src/commencer.html
packages/simulateur/src/components/FieldSiren.test.tsx
packages/simulateur/src/components/FieldSiren.tsx
packages/simulateur/src/components/MailtoLink.tsx
packages/simulateur/src/components/ds/NoSiren.tsx
packages/simulateur/src/containers/Simulateur.tsx

feat: update wording when user has no ownership

---

packages/app/src/common/models/repartition-equilibree.ts
packages/app/src/pages/ecart-rep/ecarts-membres.tsx
packages/app/src/pages/ecart-rep/validation.tsx

feat: skip publication page if all indicators are not calculable

---

.kontinuous/values.yaml
README.md
packages/api/Makefile
packages/api/egapro/dgt_repartition.py

fix representation xls naming and wording

fix: xls representation naming/wording

---

packages/app/src/common/models/repartition-equilibree.ts
packages/app/src/common/utils/date.ts
packages/app/src/design-system/base/RecapSection.tsx
packages/app/src/pages/consulter-index/recherche.tsx
packages/app/src/pages/ecart-rep/commencer.tsx
packages/app/src/pages/ecart-rep/declarant.tsx
packages/app/src/pages/ecart-rep/ecarts-cadres.tsx
packages/app/src/pages/ecart-rep/ecarts-membres.tsx
packages/app/src/pages/ecart-rep/entreprise.tsx
packages/app/src/pages/ecart-rep/periode-reference.tsx
packages/app/src/pages/ecart-rep/publication.tsx
packages/app/src/pages/ecart-rep/validation.tsx
packages/app/src/services/apiClient/repartition.ts
packages/app/src/services/apiClient/siren.ts
packages/app/src/services/apiClient/useConfig.ts

fix: percentages

---

packages/api/egapro/emails/repartition/__init__.py
packages/api/egapro/emails/repartition/body.html
packages/api/egapro/emails/repartition/body.txt
packages/api/egapro/emails/repartition/subject.txt
packages/api/egapro/models.py
packages/api/egapro/pdf/repartition.py
packages/api/egapro/views.py

add repartition email + receipt

feat: repartition receipt

---

packages/api/egapro/pdf/repartition.py
packages/api/egapro/views.py
packages/app/src/pages/ecart-rep/transmission.tsx
packages/app/src/services/apiClient/fetcher.ts
packages/app/src/services/apiClient/repartition.ts

add PDF receipt + file download
- Closes #1077

feat: add pdf receipt

---

.kontinuous/values.yaml

fix: excel naming

---

packages/simulateur/src/views/InformationsDeclarant/InformationsDeclarantForm.tsx

fix: closes Bug Index Egapro : problème avec le bouton Suivant de la page Infos déclarant #1296

---

packages/api/egapro/views.py

fix: double pdf extension

---

packages/simulateur/src/utils/helpers.ts
packages/simulateur/src/views/private/GenererTokenUtilisateurPage.tsx

fix: bug with generate token button

---

CHANGELOG.md
package.json
packages/app/src/common/utils/debug.ts
packages/app/src/common/utils/number.ts
packages/app/src/common/utils/router.ts
packages/app/src/components/layouts/App.tsx
packages/app/src/components/layouts/BasicLayout.tsx
packages/app/src/components/layouts/ConsulterIndexLayout.tsx
packages/app/src/components/layouts/RepresentationEquilibreeLayout.tsx
packages/app/src/components/layouts/RepresentationEquilibreeStartLayout.tsx
packages/app/src/pages/404.tsx
packages/app/src/pages/cgu.tsx
packages/app/src/pages/consulter-index/index.tsx
packages/app/src/pages/consulter-index/recherche.tsx
packages/app/src/pages/mentions-legales.tsx
packages/app/src/pages/politique-de-confidentialite.tsx
packages/app/src/pages/representation-equilibree/commencer.tsx
packages/app/src/pages/representation-equilibree/declarant.tsx
packages/app/src/pages/representation-equilibree/ecarts-cadres.tsx
packages/app/src/pages/representation-equilibree/ecarts-membres.tsx
packages/app/src/pages/representation-equilibree/entreprise.tsx
packages/app/src/pages/representation-equilibree/periode-reference.tsx
packages/app/src/pages/representation-equilibree/publication.tsx
packages/app/src/pages/representation-equilibree/transmission.tsx
packages/app/src/pages/representation-equilibree/validation.tsx
packages/app/src/services/apiClient/fetcher.ts
packages/app/src/services/apiClient/useFormManager.ts
packages/app/src/services/apiClient/useMe.ts
packages/app/src/services/apiClient/useUser.tsx

Closes #1309
Add JSDoc for some utils files.

feat: add consistent titles for app

---

packages/app/src/common/models/representation-equilibree.ts
packages/app/src/pages/representation-equilibree/ecarts-cadres.tsx
packages/app/src/pages/representation-equilibree/validation.tsx
packages/app/src/services/apiClient/representation.ts
packages/app/src/services/apiClient/useMe.ts

fix: validating-swr + issue #1350

---

packages/app/src/components/AlertEdition.tsx
packages/app/src/components/RepresentationEquilibree.tsx
packages/app/src/components/layouts/BasicLayout.tsx
packages/app/src/components/layouts/ConsulterIndexLayout.tsx
packages/app/src/components/layouts/RepresentationEquilibreeLayout.tsx
packages/app/src/components/layouts/RepresentationEquilibreeStartLayout.tsx
packages/app/src/pages/404.tsx
packages/app/src/pages/representation-equilibree/index.tsx
packages/app/src/pages/representation-equilibree/publication.tsx

feat: add publication date check

---

packages/simulateur/src/hooks/useSiren.ts

fix: use simpleLabel instead of label for API recherche entreprise

---

packages/app/src/pages/representation-equilibree/publication.tsx

feat: improve error mesage for date publication

---

packages/simulateur/src/containers/Simulateur.tsx
packages/simulateur/src/utils/api.ts
packages/simulateur/src/views/Declaration/Declaration.tsx
packages/simulateur/src/views/Home.tsx
packages/simulateur/src/views/ResetPage.tsx

fix: resend-receipt for updated simulations

---

packages/api/egapro/views.py

fix(api): send receipt after repeq edit

---

packages/api/egapro/csv_representation.py

fix(api): repeq search various fixes

---

packages/declaration/src/assets/js/utils.js

fix: problem getFullYear in declaration

---

packages/app/src/components/FeatureStatusProvider.tsx
packages/app/src/components/OwnersOnly.tsx
packages/app/src/components/ParamsChecker.tsx
packages/app/src/pages/ajout-declarant.tsx
packages/app/src/pages/representation-equilibree/[siren]/[year].tsx
packages/app/src/pages/representation-equilibree/commencer.tsx
packages/app/src/pages/representation-equilibree/email.tsx
packages/app/src/pages/representation-equilibree/transmission.tsx
packages/app/src/pages/representation-equilibree/validation.tsx
packages/app/src/services/apiClient/fetcher.ts
packages/app/src/services/apiClient/ownershipRequest.ts
packages/app/src/services/apiClient/useUser.tsx

Closes #1422
Création d'un utilitaire pour gérer l'état d'une feature (i. e. l'état d'une page simple avec fomulaire, qui est au début non soumises = idle, puis loading, puis en error ou en success).
- FeatureStatusProvider : provider du context
- useFeatureStatus : hook pour consommer le context
- AlertFeatureStatus : composant pour afficher une alert d'error ou de success, avec prise en compte du scroll top et d'une animation automatique

feat: add FeatureStatus context

---

packages/declaration/src/assets/js/tunnel.js

fix: problem with previous button in declaration

---

packages/simulateur/src/utils/date.ts
packages/simulateur/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx

feat: prevents simu when exists a decla

---

packages/declaration/src/assets/js/utils.js
packages/declaration/src/resultat.html

feat: closes Changer le contrôle sur la date de publication et le message d'erreur #1339

---

packages/api/egapro/schema/__init__.py
packages/api/egapro/schema/raw.yml
packages/app/src/common/models/generated.ts
packages/app/src/model.data/indicateurs/augmentations.json
packages/app/src/model.data/indicateurs/augmentations_et_promotions.json
packages/app/src/model.data/indicateurs/congés_maternité.json
packages/app/src/model.data/indicateurs/promotions.json
packages/app/src/model.data/indicateurs/rémunérations.json
packages/declaration/src/augmentations-et-promotions.html
packages/declaration/src/augmentations.html
packages/declaration/src/promotions.html
packages/declaration/src/remuneration-final.html

feat: allow percentage above 100

---

packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurCinq.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurDeux.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurDeuxTrois.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurQuatre.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurTrois.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx

feat: message recapitulatif when indicateur at None state

---

packages/simulateur/src/views/Recapitulatif/RecapitulatifIndex.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurDeux.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurDeuxTrois.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurQuatre.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurTrois.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx

feat: adapt wording for recap page

---

packages/simulateur/src/components/AnneeDeclaration.tsx
packages/simulateur/src/views/InformationsSimulation/InformationsSimulationForm.tsx

fix: not consistent error UI messages

---

packages/app/src/pages/ajout-declarant.tsx

Fix: add-declarant with emails accepted wrongly newline characters

---

packages/app/src/components/Footers.tsx
packages/app/src/components/ds/Footer.tsx
packages/app/src/components/layouts/App.tsx
packages/app/src/components/layouts/BasicLayout.tsx
packages/app/src/components/layouts/ConsultationRepeqLayout.tsx
packages/app/src/components/layouts/ConsulterIndexLayout.tsx
packages/app/src/components/layouts/RepresentationEquilibreeLayout.module.css
packages/app/src/components/layouts/RepresentationEquilibreeLayout.tsx
packages/app/src/pages/consulter-index/index.tsx
packages/app/src/pages/representation-equilibree/recherche/index.tsx
packages/app/src/pages/representation-equilibree/transmission.tsx
packages/simulateur/src/views/AskEmail.tsx

feat: footer-consultation

---

packages/declaration/src/assets/js/tunnel.js
packages/declaration/src/assets/js/utils.js
packages/declaration/src/informations.html
packages/declaration/src/perimetre.html

fix: adapt nav in decla direct with good data

---

.kontinuous/values.yaml

fix: Add redirect for simulateur old urls

---

packages/app/src/components/layouts/BasicLayoutEntreprise.tsx
packages/app/src/components/layouts/BasicLayoutPublic.tsx
packages/app/src/pages/404.tsx
packages/app/src/pages/aide-simulation.tsx
packages/app/src/pages/ajout-declarant.tsx
packages/app/src/pages/cgu.tsx
packages/app/src/pages/index.tsx
packages/app/src/pages/mentions-legales.tsx
packages/app/src/pages/politique-de-confidentialite.tsx
packages/app/src/pages/representation-equilibree/index.tsx

feat: new layout

---

packages/simulateur/src/components/ActionLink.tsx
packages/simulateur/src/components/LayoutFormAndResult.tsx
packages/simulateur/src/components/Menu.tsx
packages/simulateur/src/components/MessageForFrozenDeclaration.tsx
packages/simulateur/src/components/ResultSummary.tsx
packages/simulateur/src/components/SimulateurPage.tsx
packages/simulateur/src/containers/MainScrollView.tsx
packages/simulateur/src/containers/Simulateur.tsx
packages/simulateur/src/utils/isFrozenDeclaration.ts
packages/simulateur/src/views/Declaration/Declaration.tsx
packages/simulateur/src/views/Declaration/DeclarationForm.tsx
packages/simulateur/src/views/Effectif/Effectif.tsx
packages/simulateur/src/views/Effectif/EffectifResult.tsx
packages/simulateur/src/views/Indicateur1/IndicateurUn.tsx
packages/simulateur/src/views/Indicateur1/IndicateurUnCoef/IndicateurUnCoefGroupForm.tsx
packages/simulateur/src/views/Indicateur2/IndicateurDeux.tsx
packages/simulateur/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx
packages/simulateur/src/views/Indicateur3/IndicateurTrois.tsx
packages/simulateur/src/views/Indicateur4/IndicateurQuatre.tsx
packages/simulateur/src/views/Indicateur5/IndicateurCinq.tsx
packages/simulateur/src/views/InformationsDeclarant/InformationsDeclarant.tsx
packages/simulateur/src/views/InformationsDeclarant/InformationsDeclarantForm.tsx
packages/simulateur/src/views/InformationsEntreprise/InformationsEntreprise.tsx
packages/simulateur/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx
packages/simulateur/src/views/InformationsSimulation/InformationsSimulation.tsx
packages/simulateur/src/views/InformationsSimulation/InformationsSimulationForm.tsx
packages/simulateur/src/views/Recapitulatif/Recapitulatif.tsx

feat: disable buttons when simu are older than 1 year

---

packages/simulateur/src/components/ActionBarSingleForm.tsx
packages/simulateur/src/utils/calculsEgaProIndicateurQuatre.ts
packages/simulateur/src/views/Declaration/Declaration.tsx
packages/simulateur/src/views/Declaration/DeclarationForm.tsx
packages/simulateur/src/views/Indicateur2/IndicateurDeux.tsx
packages/simulateur/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx
packages/simulateur/src/views/Indicateur3/IndicateurTrois.tsx
packages/simulateur/src/views/Indicateur4/IndicateurQuatre.tsx
packages/simulateur/src/views/InformationsDeclarant/InformationsDeclarantForm.tsx
packages/simulateur/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx
packages/simulateur/src/views/InformationsSimulation/InformationsSimulationForm.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurDeux.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurDeuxTrois.tsx
packages/simulateur/src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx

fix: refactor simu

---

packages/simulateur/package.json
packages/simulateur/src/app-reducer.test.tsx
packages/simulateur/src/app-reducer.tsx
packages/simulateur/src/tests/calculsEgaProIndicateurDeux.test.ts
packages/simulateur/src/tests/calculsEgaProIndicateurUn.test.ts
packages/simulateur/src/utils/calculsEgaPro.ts
packages/simulateur/src/utils/calculsEgaProIndicateurCinq.ts
packages/simulateur/src/utils/calculsEgaProIndicateurDeux.ts
packages/simulateur/src/utils/calculsEgaProIndicateurTrois.ts
packages/simulateur/src/utils/calculsEgaProIndicateurUn.ts
yarn.lock

fix: sync forms and icon in menu when effectifs change

---

packages/simulateur/src/components/DeclarationsListe.tsx
packages/simulateur/src/utils/date.ts
packages/simulateur/src/views/private/ObjectifsMesuresPage.tsx

feat: freeze objectifs and mesures when 2 years is passed

---

packages/api/egapro/views.py

feat: enable last owner deletion by staff

---

packages/declaration/src/augmentations-et-promotions.html
packages/declaration/src/augmentations.html
packages/declaration/src/promotions.html
packages/declaration/src/remuneration-final.html

fix: sync problem with resultat inputs

---

packages/app/src/components/ds/Footer.tsx
packages/app/src/components/ds/TextLink.tsx
packages/app/src/pages/consulter-index/index.tsx
packages/app/src/pages/representation-equilibree/recherche/index.tsx

fix: add searchs backlinks

---

packages/app/src/common/core-domain/mappers/declarationMap.ts

fix(opmc): clean decla object on mapper

---

packages/app/src/common/core-domain/mappers/declarationMap.ts
packages/app/src/common/utils/date.ts

fix: missing time for date in persistance object

---

packages/api/egapro/views.py
packages/app/src/common/core-domain/mappers/declarationMap.ts
packages/app/src/common/utils/date.ts
packages/app/src/pages/api/debug/index.ts

fix: bug date declaration

---

packages/app/src/design-system/base/TileCompany.module.css
packages/app/src/design-system/base/client/TileCompanyIndex.module.css

fix: remove tileCompany white-space

---

packages/app/src/design-system/base/IndicatorNote.module.css
packages/app/src/design-system/base/IndicatorNote.tsx
packages/app/src/design-system/server.ts

Add IndicatorNote component.
Large version : 
```tsx
<IndicatorNote 
note={88}
max={888}
text="Nombre de points obtenus à l'indicateur"
legend="Écart en faveur des hommes"
/>
```
Small version : 
```tsx
<IndicatorNote
note={88} 
size="small" 
text="Nombre de points obtenus à l'indicateur"
/>
```
For remove border add props `noBorder` 
```tsx
<IndicatorNote 
note={88}
max={888}
text="Nombre de points obtenus à l'indicateur"
legend="Écart en faveur des hommes"
noBorder
/>
```

feat: add indicatorNote component

---

packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/(indicateurs2ou3)/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur1/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur2et3/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur2et3/Indicateur2et3Note.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur4/Form.module.scss
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur4/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur4/page.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur5/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur5/page.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/ecarts-cadres/Form.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/ecarts-membres/Form.tsx
packages/app/src/common/core-domain/computers/IndicateurCinqComputer.ts
packages/app/src/common/core-domain/computers/IndicateurQuatreComputer.ts
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts
packages/app/src/common/utils/number.ts
packages/app/src/components/RHF/NumbersPairInputs.tsx
packages/app/src/design-system/layout/FormLayout.tsx

feat(simulateurV2): indicateur 4, 5 pages

---

packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/(indicateurs2ou3)/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/(indicateurs2ou3)/Indicateur2ou3Note.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur1/CSPModeTable.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur1/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur1/Indicateur1Note.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur1/OtherModesTable.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur1/tableUtil.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur2et3/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur2et3/Indicateur2et3Note.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur4/Form.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/indicateur4/Indicateur4Note.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/recapitulatif/Recap.module.scss
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/recapitulatif/RecapSimu.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/recapitulatif/page.tsx
packages/app/src/app/(default)/index-egapro_/simulateur/(funnel)/utils.ts
packages/app/src/common/core-domain/computers/AbstractComputer.ts
packages/app/src/common/core-domain/computers/AbstractGroupComputer.ts
packages/app/src/common/core-domain/computers/IndexComputer.ts
packages/app/src/common/core-domain/computers/IndicateurDeuxComputer.ts
packages/app/src/common/core-domain/computers/IndicateurDeuxTroisComputer.ts
packages/app/src/common/core-domain/computers/IndicateurUnComputer.ts
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts
packages/app/src/design-system/base/AlternativeTable.tsx
packages/app/src/design-system/base/IndicatorNote.tsx
packages/app/src/design-system/base/Stat.tsx

feat(simulateurV2): recap page

---

.kontinuous/values.yaml
packages/api/egapro/views.py
packages/api/test/api/test_api.py
packages/app/src/pages/representation-equilibree/email.tsx
packages/app/src/services/apiClient/token.ts
packages/declaration/src/email.html
packages/simulateur/src/utils/api.ts

Décide de l'url de redirection côté serveur
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html#preventing-unvalidated-redirects-and-forwards

fix: force url redirection

---

packages/app/src/api/core-domain/infra/auth/config.ts
packages/app/src/app/(default)/Navigation.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/commencer/Form.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/entreprise/Form.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/validation/RecapRepEq.tsx
packages/app/src/app/(default)/representation-equilibree/actions.ts
packages/app/src/app/AuthHeaderItems.tsx
packages/app/src/app/ImpersonateNotice.tsx
packages/app/src/app/_globalActions/company.ts
packages/app/src/app/_globalActions/companyErrorCodes.ts
packages/app/src/app/admin/Navigation.tsx
packages/app/src/app/admin/impersonate/Form.tsx
packages/app/src/app/admin/impersonate/page.tsx
packages/app/src/app/layout.tsx
packages/app/src/common/config.ts
packages/app/src/common/core-domain/helpers/impersonate.ts
packages/app/src/common/utils/function.ts
packages/app/src/common/utils/next.ts
packages/app/src/common/utils/promise.ts
packages/app/src/middleware.ts
packages/app/tsconfig.json

feat: add staff impersonation

---

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapDeclaration.tsx
packages/app/src/design-system/base/RecapCardCompany.tsx

feat: add edit button on recap company infos

---

packages/app/src/api/core-domain/useCases/SaveDeclaration.ts
packages/app/src/app/(default)/index-egapro/declaration/commencer/CommencerForm.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Indicateur2ou3Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Indicateur1Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Indicateur2et3Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur5/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/computerHelper.ts
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/app/(default)/representation-equilibree/actions.ts
packages/app/src/app/admin/liste-referents/_actionButtons/ImportReferentsModal.tsx
packages/app/src/common/core-domain/computers/AbstractComputer.ts
packages/app/src/common/core-domain/computers/AbstractGroupComputer.ts
packages/app/src/common/core-domain/computers/IndexComputer.ts
packages/app/src/common/core-domain/computers/IndicateurCinqComputer.ts
packages/app/src/common/core-domain/computers/IndicateurDeuxComputer.ts
packages/app/src/common/core-domain/computers/IndicateurDeuxTroisComputer.ts
packages/app/src/common/core-domain/computers/IndicateurQuatreComputer.ts
packages/app/src/common/core-domain/computers/IndicateurUnComputer.ts
packages/app/src/common/core-domain/domain/specification/DeclarationSpecification.ts
packages/app/src/common/core-domain/dtos/DeclarationDTO.ts
packages/app/src/components/utils/Matomo.tsx
packages/app/src/components/utils/debug/DebugButton.tsx
packages/app/src/services/apiClient/useDeclarationFormManager.ts
packages/simulateur/src/utils/calculsEgaProIndicateurCinq.ts

feat: simu to decla

---

packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx

fix: le setValue devait faire un shouldValidate

---

packages/app/src/common/core-domain/domain/specification/DeclarationSpecification.ts

fix: constraint validation for declaration having indicator2And3

---

packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx

fix: bug computer call indicator 4

---

packages/app/src/app/(default)/index-egapro/declaration/(remunerations)/RemunerationGenericForm.tsx
packages/app/src/middleware.ts

Closes #1802
Commentaires sur les headers CSP qui ont été commentés.

fix: bug on button Suivant and validation rules

---

.kontinuous/config.yaml
.kontinuous/env/dev/values.yaml
packages/app/src/app/(default)/index-egapro/declaration/ues/UESForm.tsx

fix: bug-1805-ues

---

packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx

feat: wording congés maternité

---

packages/app/src/app/(default)/index-egapro/declaration/AlertExistingDeclaration.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapDeclaration.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/AlertEdition.tsx
packages/app/src/app/(default)/representation-equilibree/[siren]/[year]/page.tsx
packages/app/src/common/dict.ts
packages/app/src/design-system/base/RecapCardCompany.tsx

feat: forgotten wording changes

---

packages/app/src/app/(default)/index-egapro/declaration/entreprise/InformationEntreprise.tsx

feat: clean company address on declaration to avoid double informations

---

packages/app/src/app/(default)/index-egapro/declaration/confirmation/page.tsx
packages/app/src/app/(default)/index-egapro/page.tsx

feat: comment Mon Espace paragraphs and link for a while

---

packages/app/src/app/(default)/index-egapro/declaration/(remunerations)/RemunerationGenericForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations/RemunerationForm.tsx

feat: issue-1803-coef

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/hautes-remunerations/HautesRémunérationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx
packages/app/src/components/RHF/PercentageInput.tsx

feat: modify results message errors

---

packages/app/src/app/(default)/index-egapro/page.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/validation/RecapRepEq.tsx
packages/app/src/app/(default)/representation-equilibree/transmission/SendReceipt.tsx
packages/app/src/common/core-domain/helpers/entreprise.ts
packages/app/src/design-system/base/RecapCardCompany.tsx

fix #1785
fix #1829
fix #1786
PS: Le champ postalCode et city peuvent être undefined dans le cas des entreprises étrangères.

fix: closes #1785 foreign company

---

packages/app/src/api/core-domain/infra/auth/config.ts
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/pdf/route.ts
packages/app/src/app/(default)/index-egapro/declaration/actions.ts
packages/app/src/app/(default)/representation-equilibree/[siren]/[year]/page.tsx
packages/app/src/app/(default)/representation-equilibree/[siren]/[year]/pdf/route.ts
packages/app/src/app/(default)/representation-equilibree/actions.ts
packages/app/src/app/admin/liste-referents/_actionButtons/actions.ts
packages/app/src/app/admin/liste-referents/actions.ts
packages/app/src/app/api/public/referents_egalite_professionnelle/[ext]/route.ts
packages/app/src/middleware.ts

fix: Content Security Policy et revalidatePath + bug 1842 après authentification sur MonComptePro

---

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapDeclaration.tsx

feat: adapt declaration recap for 2020, 2019 and 2018

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Form.tsx
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts

feat: handle simulator raise and promotion gap with gap 0

---

packages/app/src/components/RHF/PopulationFavorable.tsx
packages/app/src/components/RHF/RadioOuiNon.tsx

fix: click on radio button must trigger validation

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Indicateur2ou3Note.tsx

feat: simulation raise gap promotion more than 250

---

packages/app/src/app/(default)/index-egapro/declaration/remunerations/RemunerationForm.tsx

feat: remove question cse when ues

---

packages/app/src/app/(default)/index-egapro/declaration/(remunerations)/RemunerationGenericForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/hautes-remunerations/HautesRémunérationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx
packages/app/src/components/RHF/IndicatorNoteInput.tsx

feat: consistency UI indicators

---

packages/app/src/app/(default)/index-egapro/declaration/(remunerations)/RemunerationGenericForm.tsx

feat: enable remove first coef for indicator 1

---

packages/app/src/app/(default)/index-egapro/objectifs-mesures/actions.ts

fix: opmc with revalidate path

---

packages/app/src/api/core-domain/useCases/SaveDeclaration.ts
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/hautes-remunerations/HautesRémunérationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/effectifs/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Form.tsx
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts
packages/app/src/common/utils/form.ts
packages/app/src/components/RHF/PercentageInput.tsx
packages/app/src/components/RHF/PopulationFavorable.tsx

Some shouldValidate was missing and didnt't trigger the validation. 
Exemple: 
Remuneration when user type 0 first, the Suivant button is disabled.

feat: consistency shouldValidate RHF

---

packages/app/src/api/core-domain/useCases/SaveDeclaration.ts
packages/app/src/api/core-domain/useCases/UpdateDeclarationWithOpMc.ts
packages/app/src/common/core-domain/domain/specification/DeclarationOpmcSpecification.ts
packages/app/src/common/core-domain/domain/specification/DeclarationSpecification.ts

fix: bug declaration specification

---

packages/app/src/app/(default)/index-egapro/page.tsx

feat: homepage egapro add ministry link

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Indicateur2et3Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/computerHelper.ts
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts
packages/app/src/components/RHF/RadioOuiNon.tsx

feat: refactor indicateur2et3

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/computerHelper.ts
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts

fix: bug parseInt was used instead of parseFloat

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/CSPModeTable.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/OtherModesTable.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/tableUtil.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/utils.ts
packages/app/src/common/core-domain/computers/AbstractGroupComputer.ts
packages/app/src/common/core-domain/computers/IndicateurDeuxComputer.ts
packages/app/src/common/core-domain/computers/utils.ts
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts

fix: indicateur1-simu

---

packages/app/src/api/core-domain/infra/mail/templates.tsx

fix: change declaration receipt mail wording

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx

feat: open new tab when send to declaration

---

packages/app/src/components/RHF/RadioOuiNon.tsx

fix: radio component validation trigger

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts

Closes #1899 
Closes #1900 
Closes #1891 
Closes #1920

fix: simulation to declaration

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/common/core-domain/computers/IndicateurDeuxComputer.ts
packages/app/src/common/core-domain/dtos/CreateSimulationDTO.ts

fix: simulation to declaration in indicator 2 or 3 allows empty strings

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/hautes-remunerations/HautesRémunérationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx

fix: get steps result values in declaration form

---

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapDeclaration.tsx

fix: get UES info in declaration recap

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/CSPModeTable.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/OtherModesTable.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/tableUtil.tsx
packages/app/src/common/core-domain/computers/utils.ts

fix: simulation indicator 1 hierarchical data handling

---

packages/app/src/app/(default)/mentions-legales/page.tsx

fix: update legal notice page

---

packages/app/src/app/(default)/politique-de-confidentialite/page.tsx

fix: update privacy policy page

---

packages/app/src/app/(default)/index-egapro/declaration/declarant/DeclarantForm.tsx
packages/app/src/components/RHF/DeclarantFields.tsx

fix: skip privacy policy checkbox on declaration

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Form.tsx

fix: simulation errors on remunerations problem

---

packages/app/src/app/(default)/mon-espace/actions.ts
packages/app/src/app/(default)/mon-espace/mes-declarations/SelectSirenStaff.tsx
packages/app/src/app/(default)/mon-espace/mes-declarations/page.tsx
packages/app/src/app/AuthHeaderItems.tsx
packages/app/src/app/HeaderAccountMenu.tsx
packages/app/src/app/root.module.scss

Closes #1949
Closes #1946
Closes #1945

feat: Declaration list staff view & account menu

---

packages/app/src/app/(default)/index-egapro/declaration/declarant/DeclarantForm.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/declarant/Form.tsx
packages/app/src/components/RHF/DeclarantFields.tsx

fix: remove deprecated privacy policy checkbox

---

packages/app/src/app/(default)/index-egapro/declaration/hautes-remunerations/HautesRémunérationsForm.tsx

fix: declaration step 11 isValid state

---

packages/app/src/api/core-domain/infra/auth/config.ts
packages/app/src/api/core-domain/repo/IOwnershipRepo.ts
packages/app/src/api/core-domain/repo/impl/PostgresOwnershipRepo.ts
packages/app/src/api/core-domain/useCases/SyncOwnership.ts
packages/app/src/app/(default)/mon-espace/actions.ts
packages/app/src/app/(default)/mon-espace/gerer-utilisateurs/SirenInput.tsx
packages/app/src/app/(default)/mon-espace/gerer-utilisateurs/page.tsx
packages/app/src/app/(default)/mon-espace/mes-entreprises/SelectSiren.tsx
packages/app/src/app/(default)/mon-espace/mes-entreprises/page.tsx
packages/app/src/app/HeaderAccountMenu.tsx

feat: manage users / my companies

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur4/Form.tsx
packages/app/src/common/core-domain/computers/AbstractGroupComputer.ts

fix: equality conditions and maternity raise

---

packages/app/src/common/core-domain/computers/IndicateurCinqComputer.ts

fix: indicator 5 canCompute

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Form.tsx

fix: non calculable indicator 2 and 3

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Form.tsx

fix: non calculable indicator 2 or 3

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx

fix: declaration non calculable motifs mandatories

---

packages/app/src/app/(default)/mon-espace/mes-declarations/page.tsx

- redirect if not logged in
- switch to getCompany to get name

fix: fetch companies and redirect on my declarations page

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts

fix: carry simu to decla non computable indicators

---

packages/app/src/app/(default)/mon-espace/mes-declarations/IndexList.tsx
packages/app/src/app/(default)/mon-espace/mes-declarations/RepeqList.tsx
packages/app/src/app/(default)/mon-espace/mes-declarations/page.tsx
packages/app/src/app/HeaderAccountMenu.tsx

fix: declarations list company view

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts

fix: RecapToSimu take nonWeighted result for indicator1, 2or3

---

packages/app/src/app/(default)/index-egapro/declaration/confirmation/page.tsx
packages/app/src/app/(default)/index-egapro/page.tsx

fix: enable links to my declaration page

---

packages/app/src/api/core-domain/useCases/UpdateDeclarationWithOpMc.ts
packages/app/src/common/core-domain/domain/specification/DeclarationOpmcSpecification.ts

fix: opmc declaration

---

packages/app/src/app/(default)/aide-moncomptepro/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/commencer/CommencerForm.tsx
packages/app/src/app/(default)/index-egapro/page.tsx
packages/app/src/app/(default)/login/MonCompteProLogin.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/commencer/Form.tsx
packages/app/src/app/(default)/representation-equilibree/page.tsx

feat: add MCP help page and links

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/common/core-domain/domain/valueObjects/declaration/indicators/NotComputableReason.ts
packages/app/src/common/core-domain/domain/valueObjects/declaration/indicators/NotComputableReasonSalaryRaisesAndPromotions.ts

Closes #2001
Closes #2003 
Closes #2004 
Closes #2005

fix: simu to decla indicator 2,3,4

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur4/Indicateur4Note.tsx

fix: indicator 4 nc card

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Indicateur1Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/tableUtil.tsx

fix: wordings

---

packages/app/src/app/(default)/mon-espace/les-entreprises/SirenInput.tsx
packages/app/src/app/(default)/mon-espace/les-entreprises/page.tsx
packages/app/src/app/(default)/mon-espace/mes-entreprises/SelectSiren.tsx
packages/app/src/app/(default)/mon-espace/mes-entreprises/page.tsx
packages/app/src/app/HeaderAccountMenu.tsx
packages/app/src/middleware.ts

fix: company page

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Indicateur1Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx

fix: result text in recap for indicator 1

---

packages/app/src/common/core-domain/computers/IndicateurDeuxTroisComputer.ts

fix: ifadvantage message for indicator 2 and 3

---

packages/app/src/app/(default)/aide-moncomptepro/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/commencer/CommencerForm.tsx
packages/app/src/app/(default)/index-egapro/page.tsx
packages/app/src/app/(default)/login/MonCompteProLogin.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/commencer/Form.tsx
packages/app/src/app/(default)/representation-equilibree/page.tsx

fix: MCP help links

---

packages/app/src/app/(default)/aide-moncomptepro/page.tsx

fix: MCP help text

---

packages/app/src/common/core-domain/computers/DeclarationComputer.ts

fix: compute error on declaration

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts
packages/app/src/common/core-domain/computers/IndicateurQuatreComputer.ts

fix: indic 4 simu to decla

---

packages/app/src/app/(default)/index-egapro/declaration/confirmation/page.tsx

fix: link to my declaration page

---

packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/commencer/page.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/declarant/page.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/publication/Form.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/titles.ts
packages/app/src/app/(default)/representation-equilibree/(funnel)/validation/page.tsx
packages/app/src/app/(default)/representation-equilibree/Recap.tsx
packages/app/src/common/core-domain/dtos/CreateRepresentationEquilibreeDTO.ts
packages/app/src/common/core-domain/dtos/helpers/common.ts
packages/app/src/design-system/base/RecapCardCompany.tsx

fix: wording in repeq funnel

---

packages/app/src/app/HeaderAccountMenu.tsx

feat: add MCP link to account menu

---

packages/app/src/app/(default)/index-egapro/simulateur/commencer/page.tsx

fix: add no save warn message on simu start

---

packages/app/src/app/(consultation)/layout.tsx
packages/app/src/app/(default)/layout.tsx
packages/app/src/app/Footer.tsx
packages/app/src/app/admin/layout.tsx
packages/app/src/app/error.tsx
packages/app/src/app/error/page.tsx

fix: update footer links

---

packages/app/src/api/core-domain/infra/pdf/templates/BaseReceiptTemplate.tsx
packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx

fix: update declaration PDF receipts

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Form.tsx

fix: hide tooltip simu indic2-3 when form empty

---

packages/app/src/app/(default)/index-egapro/declaration/confirmation/page.tsx

fix: add survey button on index declaration

---

packages/app/src/app/(default)/index-egapro/declaration/declarant/page.tsx
packages/app/src/app/(default)/login/page.tsx
packages/app/src/app/(default)/mon-espace/mes-entreprises/page.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/declarant/page.tsx
packages/app/src/app/HeaderAccountMenu.tsx

Closes #2034 
Closes #2036 
& fixes header menu link

fix: update MCP link based on env

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx
packages/app/src/components/RHF/DeclarantFields.tsx
packages/app/src/components/RHF/PercentageInput.tsx

fix: add hint text in declaration input fields

---

packages/app/src/app/Footer.tsx

fix: udpate referents footer link

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Indicateur2ou3Note.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx

fix: wording simu recap indicator 2 & 3

---

packages/app/src/api/core-domain/infra/mail/templates.tsx
packages/app/src/api/core-domain/useCases/SendOpmcReceipt.ts
packages/app/src/app/(default)/index-egapro/objectifs-mesures/actions.ts

fix: update opmc receipt email

---

packages/app/src/api/core-domain/infra/auth/MonCompteProProvider.ts
packages/app/src/app/(default)/index-egapro/declaration/declarant/DeclarantForm.tsx

fix: add phone number from MCP in declarant form

---

packages/app/src/app/(default)/index-egapro/objectifs-mesures/[siren]/[year]/ObjectifsMesuresForm.tsx

fix: wording on OPMC declaration

---

packages/app/src/app/(default)/index-egapro/declaration/periode-reference/PeriodeReferenceForm.tsx
packages/app/src/common/utils/form.ts

fix: allow 0 in workforce count

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx

fix: change input field type in raises rate form

---

packages/app/src/app/global.css

fix: display stepper in declaration

---

packages/app/src/app/(default)/mon-espace/mes-declarations/IndexList.tsx
packages/app/src/app/(default)/mon-espace/mes-declarations/page.tsx

fix: my declarations wording and sorting

---

packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx
packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx
packages/app/src/components/utils/getModifiedFormValues.tsx

fix: remove stale form data when editing declaration

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/effectifs/Form.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/OtherModesTable.tsx
packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/tableUtil.tsx
packages/app/src/common/utils/form.ts

fix: delete spaces when copy paste

---

packages/app/src/api/core-domain/infra/pdf/templates/BaseReceiptTemplate.tsx
packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx
packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/confirmation/page.tsx

fix: declaration and repeq receipt pdf formatting

---

packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx

Fixes https://github.com/SocialGouv/egapro/issues/2095#issuecomment-1932232574

fix: formatting declaration receipt field

---

packages/app/src/api/core-domain/infra/auth/MonCompteProProvider.ts
packages/app/src/middleware.ts

fix: csp headers for matomo

---

packages/app/src/api/core-domain/useCases/SaveDeclaration.ts

fix: update index when modified declaration is NC

---

packages/app/src/app/(default)/mon-espace/mes-declarations/page.tsx

fix: improve siren validation and selection in my-declarations

---

packages/app/src/api/core-domain/infra/auth/MonCompteProProvider.ts
packages/app/src/components/RHF/DeclarantFields.tsx

fix: format and check phone number from MCP data

---

packages/app/src/app/(default)/index-egapro/declaration/confirmation/page.tsx

fix: open new window from declaration confirmation to OPMC

---

packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx

fix: declaration pdf receipt formatting and wording

---

packages/app/src/app/(default)/login/page.tsx

fix: login page helper text wording

---

packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx

fix: repeq receipt formatting

---

packages/app/src/design-system/base/client/TileCompanyIndex.tsx

fix: range label in site consultation

---

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapCardIndicator.tsx
packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx

Fixes https://github.com/SocialGouv/egapro/issues/2131#issuecomment-1952944970
Fixes https://github.com/SocialGouv/egapro/issues/2131#issuecomment-1952948842

fix: Declaration recap indicators wording

---

packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx
packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx

Fixes https://github.com/SocialGouv/egapro/issues/2094#issuecomment-1954397285

fix: Declaration receipt long publication url handling

---

packages/app/src/common/utils/form.ts

fix: Declarant form phone number error wording

---

packages/app/src/common/core-domain/mappers/declarationMap.ts

fix: Declaration data to DTO when default data missing

---

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/EditButton.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/commencer/CommencerForm.tsx

fix: edit existing declaration from recap

---

packages/app/src/api/core-domain/infra/mail/templates.tsx

Closes #2059
Closes #2060
Closes #2086
Closes #2105

feat: add logo and header to mail templates

---

packages/app/src/app/(default)/mon-espace/mes-declarations/IndexList.tsx

fix: my-delcarations page OPMC wording

---

packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx
packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx
packages/app/src/design-system/base/RecapCardCompany.tsx

fix: Default if NAF code description not available

---

packages/app/src/api/core-domain/repo/impl/PostgresDeclarationRepo.ts
packages/app/src/app/(default)/mon-espace/mes-declarations/IndexList.tsx

fix: handle declarations with missing data or insufficient duration

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx

fix: recap simu wording

---

packages/app/src/design-system/base/client/TileCompanyIndex.module.css

Fixes https://github.com/SocialGouv/egapro/issues/2152#issuecomment-1973212401

fix: Consultation page company details formatting

---

packages/app/src/api/core-domain/infra/mail/templates.tsx

fix: declaration receipt high renumerations missing wording when non calculable

---

packages/app/src/api/core-domain/infra/pdf/templates/DeclarationReceipt.tsx
packages/app/src/api/core-domain/infra/pdf/templates/RepresentationEquilibreeReceipt.tsx
packages/app/src/app/(default)/index-egapro/declaration/commencer/CommencerForm.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/entreprise/Form.tsx
packages/app/src/app/(default)/representation-equilibree/(funnel)/validation/RecapRepEq.tsx
packages/app/src/common/core-domain/helpers/entreprise.ts

fix: wording and allow if company has privated data

---

packages/app/src/api/core-domain/useCases/SaveDeclaration.ts
packages/app/src/app/(default)/index-egapro/declaration/AlertExistingDeclaration.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/EditButton.tsx
packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/page.tsx
packages/app/src/app/(default)/index-egapro/declaration/actions.ts
packages/app/src/app/(default)/representation-equilibree/[siren]/[year]/page.tsx

feat: staff can edit declaration if older than one year

---

.kontinuous/values.yaml
packages/api/egapro/bin.py
packages/api/setup.cfg
packages/api/start.sh

Enable with `SCHEDULER: "True"` in env

feat: python API export tasks scheduler

---

packages/app/src/app/(default)/aide-moncomptepro/page.tsx

fix: MCP help page wording

---

packages/app/src/app/(default)/login/page.tsx

fix: MCP login page wording

---

packages/app/src/app/Footer.tsx
packages/app/src/app/api/public/referents_egalite_professionnelle/[ext]/route.ts

fix: Replace referents export URL by API export

---

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/page.tsx

fix: Simulateur final step wording

---

packages/app/src/app/(consultation)/SearchSirenForm.tsx
packages/app/src/app/(consultation)/index-egapro/recherche/page.tsx
packages/app/src/app/(consultation)/representation-equilibree/recherche/page.tsx

fix: Search form wording

---

packages/app/src/api/core-domain/infra/mail/templates.tsx
packages/app/src/api/core-domain/repo/IReferentRepo.ts
packages/app/src/api/core-domain/repo/impl/PostgresReferentRepo.ts
packages/app/src/api/core-domain/useCases/SendDeclarationReceipt.ts
packages/app/src/api/core-domain/useCases/SendOpmcReceipt.ts
packages/app/src/api/core-domain/useCases/SendRepresentationEquilibreeReceipt.ts
packages/app/src/app/(default)/index-egapro/declaration/actions.ts
packages/app/src/app/(default)/index-egapro/objectifs-mesures/actions.ts
packages/app/src/app/(default)/representation-equilibree/actions.ts

fix: mail templates wording and add referent

---

packages/app/src/app/(default)/mon-espace/les-entreprises/page.tsx
packages/app/src/app/(default)/mon-espace/mes-entreprises/page.tsx

fix: my company page info wording
