SocialGouv/egapro

package.json
Fixes #154
Change the `package.json` `test` script entry so it doesn't run tests in interactive watch mode by default, so lerna doesn't hang (waiting for a user input).
=> Run the app tests without watch mode when using lerna

packages/app/src/components/ErrorMessage.tsx, packages/app/src/containers/Simulateur.tsx, packages/app/src/views/Home.tsx, packages/app/src/views/ModalEmail.tsx
Fixes #152
This is very crude at the moment, but at least we get some feedback on API failures:
Failure when getting the code:
Failure when sending the email:
Failure when getting the data associated with the code
Failure when saving the data
There are not tests for it (yet?) as we would need to test the rendering and some events (clicking on buttons, entering emails, data...) and it seems we have nothing in place right now for that.
We might want to use [the react testing library](https://testing-library.com/) (also used on the "code du travail numérique").
@tglatt thoughts?
=> Display an error on API failure

packages/app/src/components/Menu.tsx, packages/app/src/data/faq.tsx, packages/app/src/views/Effectif/Effectif.tsx, packages/app/src/views/Indicateur1/IndicateurUn.tsx, packages/app/src/views/Indicateur2/IndicateurDeux.tsx, packages/app/src/views/Indicateur3/IndicateurTrois.tsx, packages/app/src/views/Indicateur4/IndicateurQuatre.tsx, packages/app/src/views/Indicateur5/IndicateurCinq.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurCinq.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurDeux.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurQuatre.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurTrois.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx
Fixes #159
This renames all the indicators by either removing their number
- in the left menu
- in the page titles
- in the FAQ titles
Or replacing the number by the full indicator name
- in the FAQ content
- in the recap page
=> Remove indicators numbers

packages/app/src/AppReducer.test.tsx, packages/app/src/AppReducer.tsx, packages/app/src/__fixtures__/stateComplete.tsx, packages/app/src/__fixtures__/stateCompleteAndValidate.tsx, packages/app/src/__snapshots__/AppReducer.test.tsx.snap, packages/app/src/components/Menu.tsx, packages/app/src/components/RadioButtons.tsx, packages/app/src/containers/MainScrollView.tsx, packages/app/src/containers/Simulateur.tsx, packages/app/src/globals.d.ts, packages/app/src/utils/__snapshots__/calculsEgaProIndicateurDeuxTrois.test.tsx.snap, packages/app/src/utils/calculsEgaPro.tsx, packages/app/src/utils/calculsEgaProIndicateurDeuxTrois.test.tsx, packages/app/src/utils/calculsEgaProIndicateurDeuxTrois.tsx, packages/app/src/utils/formHelpers.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTroisForm.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTroisResult.tsx, packages/app/src/views/Indicateur2et3/index.js, packages/app/src/views/Recapitulatif/Recapitulatif.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurDeux.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurDeuxTrois.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurTrois.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurUn.tsx, packages/app/src/views/Recapitulatif/components/RowData.tsx
Fixes #160
- [ ] ~~si "autre période de référence" (pluri-annuelles) sélectionné, ne pas afficher le radiobutton "il y a eu/pas eu d'augmentations ou promotions"~~
=> Nouvelle page indicateur 2 et 3 écart de taux d'augmentations et de promotions

packages/app/src/AppReducer.test.tsx, packages/app/src/AppReducer.tsx, packages/app/src/__fixtures__/stateComplete.tsx, packages/app/src/__fixtures__/stateCompleteAndValidate.tsx, packages/app/src/__snapshots__/AppReducer.test.tsx.snap, packages/app/src/components/Input.tsx, packages/app/src/components/Menu.tsx, packages/app/src/components/RadioLabels.tsx, packages/app/src/containers/MainScrollView.tsx, packages/app/src/containers/Simulateur.tsx, packages/app/src/globals.d.ts, packages/app/src/utils/formHelpers.tsx, packages/app/src/utils/helpers.test.tsx, packages/app/src/utils/helpers.tsx, packages/app/src/views/Effectif/Effectif.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTroisForm.tsx, packages/app/src/views/Informations/Informations.tsx, packages/app/src/views/Informations/InformationsForm.tsx, packages/app/src/views/Informations/InformationsResult.tsx, packages/app/src/views/Informations/index.js, packages/app/src/views/Recapitulatif/Recapitulatif.tsx, packages/app/src/views/Recapitulatif/RecapitulatifInformations.tsx
Fixes #161 
- [ ] lors d'une modification de la tranche d'effectifs, invalider les indicateurs liés
=> Nouvelle page informations entreprise et période de référence

packages/app/src/components/FormAutoSave.tsx, packages/app/src/views/Informations/InformationsForm.tsx
Fixes #239
Quand on change de tranche d'effectifs, même si on revient sur la valeur d'origine on met à jour le menu.
=> fix(informations): toujours mettre à jour le menu quand on change d'effectifs

packages/app/package.json, packages/app/src/utils/api.js
Utilisation du mode `proxy` de `create-react-app` : permet de tester sur IE11 dans une virtualbox, même en mode dev (sinon l'url de l'API n'est pas accessible sur http://localhost:4000).
=> Test on IE11

packages/app/src/utils/helpers.test.tsx, packages/app/src/utils/helpers.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTrois.tsx, packages/app/src/views/Indicateur2et3/IndicateurDeuxTroisResult.tsx, packages/app/src/views/Recapitulatif/Recapitulatif.tsx, packages/app/src/views/Recapitulatif/RecapitulatifIndicateurDeuxTrois.tsx
Fixes #244
Pour info, à l'heure actuelle la bulle de résultat affiche l'écart de taux d'augmentation, ainsi que le nombre équivalent salariés. En attendant une meilleure présentation, le titre a été changé de "votre résultat final est xx%" à "votre écart de taux d'augmentation est xx%".
=> fix(indicateur2et3): meilleure présentation de l'écart de taux d'augmentation

packages/app/src/components/Footer.tsx, packages/app/src/views/Recapitulatif/Recapitulatif.tsx
Fixes #105
Rajout du bouton "mon avis" en fin de page de récapitulatif. Par ailleurs le lien "donnez-nous votre avis" dans le footer pointer sur le même lien:
=> feat(bouton mon avis): ajout d'un bouton "mon avis" en fin de récapitulatif

packages/app/src/AppReducer.test.tsx, packages/app/src/AppReducer.tsx, packages/app/src/__fixtures__/stateComplete.tsx, packages/app/src/__snapshots__/AppReducer.test.tsx.snap, packages/app/src/globals.d.ts, packages/app/src/views/InformationsComplementaires/InformationsComplementairesForm.tsx, packages/kinto/import-solen.py, packages/kinto/json-schema.json
Fixes #422
Il y a aussi la donnée `anneeDeclaration` qui est passée en `integer` au lieu de `string`
=> fix(declaration): datePublication et lienPublication déplacés dans informationsComplementaires

packages/app/src/components/RegionsDepartements.tsx
Sur la page http://418a6-egapro.dev.factory.social.gouv.fr/simulateur/881797ae-6cff-4e9b-9d03-3285b2e4b52b/informations-entreprise il y a une erreur JS (undefined).
=> Fix(declaration): fix undefined

.gitlab-ci/stages/05-deploy.yml, .gitlab-ci/stages/06-release.yml
À l'heure actuelle avec le job import-export dans l'étape 05-deploy il n'est
pas possible de faire une mise en preprod (06-release) si le job import-export
n'a pas été effectué.
=> fix(ci): déplacement du job import-export dans l'étape 06-release

packages/import-export/Dockerfile
This should prevent `error: pathspec 'v2-9-2' did not match any file(s) known to git`
=> fix(import-export): proper git checkout for a tag

src/utils/helpers.tsx
Return percentages as a number between 0 and 100 instead of between 0 and 1 for the API
=> /!\ only merge this once the API is ready

src/utils/helpers.tsx
Erreur de l'API disant que publicationDate est manquante.
publicationDate ne doit pas être envoyée qd l'index est non calculable.
Mais il doit l'être pour un index à 0.
=> fix: for 2019 decla and index calculable but 0

src/containers/AppLayout.tsx, src/containers/Simulateur.tsx, src/views/Declaration/Declaration.tsx, src/views/Declaration/DeclarationForm.tsx, src/views/ResetPage.tsx
Pour éviter que les utilisateurs réutilisent un même id de simulation pour faire plusieurs déclarations. 
Rien ne les empêche de le faire encore mais avec ce nouveau bouton, il leur sera plus pratique de ne pas le faire.
=> feat: ajouter un bouton à la fin d'une décla réussie

src/views/Declaration/Declaration.tsx
À la suite d'un refactor, j'ai modifié l'appel à validateDeclaration, une action du reducer. 
Or j'ai utilisé un spread opérateur, qui n'a pas détecté que les objets passés en paramètre n'était pas bon. 
Fixé.
=> fix: error in Declaration page, with spread operator

src/theme/components.ts
#868 Fix :  Il faut bloquer la liste de choix des années des indicateurs dans les informations de la simulation quand on est en mode lecture
=> fix: remove pointer events on select when is readonly

packages/simulateur/src/components/AuthContext.tsx, packages/simulateur/src/views/Declaration/Declaration.tsx
Closes #1005
J'ai tenté initialement d'invoquer la nouvelle fonction refreshAuth dans la page MesDeclarations, là où était constaté le problème, mais j'avais alors une boucle infinie de useEffect.
En effet, PrivateRoute affiche un Spinner quand l'auth est en cours, donc le composant MesDeclarations en dessous est unmount. Puis quand l'auth est finie, PrivateRoute mount ce composant, et si ce composant relance l'authentification via un useEffect au mount, cela va avoir un impact sur PrivateRoute, qui va unmount le composant, etc..
J'ai réglé ça en faisant le refresh à la source du changement, c'est à dire dans la dernière page du wizard, la page qui crée réellement la déclaration et qui déclenche un traitement côté API qui va créer automatiquement le ownership entre ce user et ce SIREN.
=> fix: user rights have to be updated after a declaration

packages/simulateur/.env
Le simulateur, contrairement à la déclaration directe, utilisait par défaut l'API de la préprod.
On commente dans le .env pour avoir la même config entre les fronts.
=> feat: comment env in order to have api on localhost

packages/declaration/src/assets/js/utils.js, packages/declaration/src/commencer.html, packages/simulateur/src/components/FieldSiren.test.tsx, packages/simulateur/src/components/FieldSiren.tsx, packages/simulateur/src/utils/api.ts, packages/simulateur/src/views/InformationsEntreprise/InformationsEntreprise.tsx, packages/simulateur/src/views/InformationsEntreprise/InformationsEntrepriseForm.tsx, packages/simulateur/src/views/InformationsEntreprise/components/EntrepriseUESInputField.tsx
- closes #961 
---
Côté simulation, j'ai dû adapter le composant `FieldSiren`. Ce composant est à refactor car il est géré par React Hook Form et un système de composition de validator, qui ne sont pas adaptés pour notre cas. 
- les fonctions de validation ne prennent en paramètre que l'input en cours et tous les autres inputs du form. Pas de chance, notre validation porte sur le champ qui fait partie d'un autre form (vu qu'on est dans un wizard, les contraintes inter champs peuvent être sur des champs non présents dans l'écran courant). J'ai dû faire un function builder, qui prend l'année en paramètre et qui rend le validator dans la forme attendu par React Hook Form...
- comme notre state/dispatch n'utilise pas de contexte, j'ai dû passer year de `InformationsEntreprise` à …
=> feat: adapt to changes on validate-siren endpoint

packages/api/egapro/helpers.py, packages/api/test/api/test_ownership.py
- Fixes #1378 
- header `Referer: egapro` added for both api.gouv entreprise api, and Fabrique's "recherche-entreprise" api
=> fix: add referer before calling entreprise api

packages/api/egapro/sql/search_representation_equilibree.sql, packages/api/test/test_ft.py
- Ref: #1325 
- handle whatever weird float is found is jsonb data field
e.g. : (all are ok now)
```json
{
"pourcentage_femmes_cadres": "49.1",
"pourcentage_hommes_cadres": "50,9",
"pourcentage_femmes_membres": 49.1
}
```
=> fix(api): handle floats and float string in jsonb after repeqsearch

.kontinuous/env/preprod/values.yaml, .kontinuous/env/prod/values.yaml
The aim is to to fine tune `api` & `app` pods requests and limits on `preprod` and `prod` environments.
=> chore: set pods requests limits

packages/app/src/api/core-domain/repo/IOwnershipRequestRepo.ts, packages/app/src/api/core-domain/repo/impl/PostgresOwnershipRequestRepo.ts, packages/app/src/api/core-domain/useCases/GetOwnershipRequest.ts, packages/app/src/common/core-domain/dtos/OwnershipRequestDTO.ts, packages/app/src/pages/admin/liste-declarants.tsx, packages/app/src/services/apiClient/useListeDeclarants.ts, packages/app/src/services/apiClient/useOwnershipRequestListStore.tsx
- Closes #1575
- replace "siren" search field with a "query" search field
- in backend, query can search on chosen column (for now "asker_email", "email", and "siren")
- search is now case wide and case insensitive (i.e. `where column ilike %value%`)
=> feat(bo): allow searching by email in liste declarants

packages/declaration/Dockerfile.dev
Problème lors du `yarn dev:declaration`
Le problème vient de la version utilisée dans docker.dev (juste 4, sans précision) et du fait que l'équipe Jekyll a fait un breaking change sans changer la version majeure de l'image Docker. Fonctionne en précisant la version exacte 4.2.0.
=> fix: problem with jekyll 4 in docker dev

packages/app/src/design-system/base/BigNote.module.scss, packages/app/src/design-system/base/BigNote.tsx, packages/app/src/design-system/server.ts
Usage
```
<BigNote
legend={<>Index de&nbsp;:</>}
note={88}
text={
<>
<p>
Total des points obtenus aux indicateurs calculables&nbsp;: <strong>60</strong>
</p>
<p>
Nombre de points maximum pouvant être obtenus aux indicateurs calculables&nbsp;: <strong>75</strong>
</p>
</>
}
max={100}
/>
```
Add props `noBorder` for remove border like
```
<BigNote
noBorder
legend={<>Index de&nbsp;:</>}
note={88}
text={
<>
<p>
Total des points obtenus aux indicateurs calculables&nbsp;: <strong>60</strong>
</p>
<p>
Nombre de points maximum pouvant être obtenus aux indicateurs calculables&nbsp;: <strong>75</strong>
</p>
</>
}
max={100}
/>
```
=> feat: add BigNote component

packages/app/src/api/core-domain/useCases/SaveDeclaration.ts, packages/app/src/app/(default)/index-egapro/declaration/(remunerations)/RemunerationGenericForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/actions.ts, packages/app/src/app/(default)/index-egapro/declaration/augmentations-et-promotions/AugmentationsEtPromotionsForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/augmentations/AugmentationsForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/commencer/CommencerForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/conges-maternite/CongesMaterniteForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/hautes-remunerations/HautesRémunérationsForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/promotions/PromotionsForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/remunerations-resultat/RemunerationResultatForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/ues/UESForm.tsx, packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/simuToDecla.ts, packages/app/src/app/(default)/messages.tsx, packages/app/src/common/core-domain/computers/AbstractComputer.ts, packages/app/src/common/core-domain/computers/DeclarationComputer.ts, packages/app/src/common/core-domain/domain/specification/DeclarationSpecification.ts, packages/app/src/common/core-domain/dtos/DeclarationDTO.ts, packages/app/src/common/core-domain/mappers/declarationMap.ts, packages/app/src/common/utils/form.ts, packages/app/src/components/RHF/IndicatorNote.module.css, packages/app/src/components/RHF/IndicatorNoteInput.tsx, packages/app/src/components/RHF/PercentageInput.tsx, packages/app/src/components/RHF/PopulationFavorable.tsx
fix #1777
- utilisation de "" comme valeur par défaut des inputs de formulaire pour les champs résultat et Percentage. (considered to be a [good practice by official React doc](https://react.dev/reference/react-dom/components/input#im-getting-an-error-a-component-is-changing-an-uncontrolled-input-to-be-controlled))
- refactor des messages d'erreur des formulaires dans un fichier messages.ts, afin d'avoir plus d'homogénéité dans les messages côté UI
=> fix: bug 1777 population favorable

packages/app/src/app/(default)/index-egapro/declaration/publication/PublicationForm.tsx
=> feat: change publication communication empty message error

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur2et3/Form.tsx
Régression par rapport au refactor fait hier sur le Form pour l'indicateur 2 ou l'indicateur 3.
=> fix: écart valeur absolue was hidden wrongly

packages/app/src/app/(default)/index-egapro/objectifs-mesures/[siren]/[year]/ObjectifsMesuresForm.tsx
=> fix: trim extra spaces in objective form

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/(indicateurs2ou3)/Indicateur2ou3Note.tsx, packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/Indicateur1Note.tsx, packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/IndicatorNote1.module.css, packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/tableUtil.tsx
=> fix: simulation indicator 1, 2 and 3

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx, packages/app/src/common/core-domain/computers/AbstractGroupComputer.ts, packages/app/src/common/core-domain/computers/IndicateurDeuxComputer.ts, packages/app/src/common/core-domain/computers/IndicateurUnComputer.ts
=> fix: display non-weighted gaps in simu recap

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/recapitulatif/RecapSimu.tsx
=> fix: display nc on simu recap gap in rate increases

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapDeclaration.tsx
=> fix: declaration recap wording when effective count is 0

packages/app/src/app/(default)/index-egapro/declaration/[siren]/[year]/RecapCardIndicator.tsx, packages/app/src/app/(default)/index-egapro/declaration/remunerations/RemunerationForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/resultat-global/ResultatGlobalForm.tsx
=> fix: sync modified data state in déclaration indicator rénumeration

packages/app/src/app/(default)/index-egapro/declaration/remunerations/RemunerationForm.tsx, packages/app/src/app/(default)/index-egapro/declaration/resultat-global/ResultatGlobalForm.tsx
=> fix: Prevent 0 on renumeration results step if declaration modified

packages/app/src/common/core-domain/domain/declaration/indicators/PromotionsIndicator.ts, packages/app/src/common/core-domain/domain/declaration/indicators/RemunerationsIndicator.ts, packages/app/src/common/core-domain/domain/declaration/indicators/SalaryRaisesAndPromotionsIndicator.ts, packages/app/src/common/core-domain/domain/declaration/indicators/SalaryRaisesIndicator.ts
=> fix: allow over 100% results for promotion, renumeration and raises indicators

packages/app/src/app/(default)/index-egapro/simulateur/(funnel)/indicateur1/tableUtil.tsx
=> fix: remove average salaries calculation in simulation

.yarn/patches/@codegouvfr-react-dsfr-npm-0.78.2-9b92c7917d.patch, packages/app/package.json, packages/app/src/app/Footer.tsx, yarn.lock
=> fix: fix site links
